<?php

return [
    'name' => "Admin",
    'css' => [
        'admin/frest-admin/app-assets/vendors/css/vendors.min.css',
        'admin/frest-admin/app-assets/vendors/css/forms/select/select2.min.css',
        'admin/frest-admin/app-assets/css/bootstrap.min.css',
        'admin/frest-admin/app-assets/css/bootstrap-extended.min.css',
        'admin/frest-admin/app-assets/css/colors.min.css',
        'admin/frest-admin/app-assets/css/components.min.css',
        'admin/frest-admin/app-assets/css/themes/dark-layout.min.css',
        'admin/frest-admin/app-assets/css/themes/semi-dark-layout.min.css',
        'admin/frest-admin/app-assets/css/core/menu/menu-types/horizontal-menu.min.css',
        'admin/frest-admin/app-assets/css/pages/authentication.css',
        'admin/frest-admin/app-assets/vendors/css/extensions/toastr.css',
        'admin/frest-admin/app-assets/css/plugins/extensions/toastr.min.css',
        'admin/frest-admin/assets/css/style.css',
        'admin/css/custom.css',
    ],
    'js'  => [
        'admin/frest-admin/app-assets/vendors/js/vendors.min.js',
        'admin/frest-admin/app-assets/fonts/LivIconsEvo/js/LivIconsEvo.tools.min.js',
        'admin/frest-admin/app-assets/fonts/LivIconsEvo/js/LivIconsEvo.defaults.min.js',
        'admin/frest-admin/app-assets/fonts/LivIconsEvo/js/LivIconsEvo.min.js',
        'admin/frest-admin/app-assets/vendors/js/ui/jquery.sticky.js',
        'admin/frest-admin/app-assets/vendors/js/extensions/toastr.min.js',
        'admin/frest-admin/app-assets/js/scripts/configs/horizontal-menu.min.js',
        'admin/frest-admin/app-assets/js/core/app-menu.min.js',
        'admin/frest-admin/app-assets/js/core/app.min.js',
        'admin/frest-admin/app-assets/js/scripts/components.min.js',
        'admin/frest-admin/app-assets/js/scripts/footer.min.js',
        'admin/frest-admin/app-assets/js/scripts/jquery.slimscroll.js',
        'admin/frest-admin/app-assets/js/scripts/customizer.min.js',
        'admin/frest-admin/app-assets/vendors/js/forms/select/select2.full.min.js',
        'admin/libs/bootstrap-maxlength/bootstrap-maxlength.min.js',
        'js/library/sweetalert2.all.min.js',
        'js/lang.js',
        'js/core.js',
        'admin/js/vue.js',
        'admin/js/app.js',
        'admin/js/admin.js',
        'js/slugify.js',
        'admin/js/axios.min.js',
    ],
    'favicon' => 'favicon.gif'
];