<?php

return [
    'backend' => [
        //'gallery'       => ['controller'=>'Gallery','title' => 'Thư viện Ảnh'],
        'category'      => ['controller'=>'Category','title' => 'Danh Mục'],
        //'customer'      => ['controller'=>'Customer','title' => 'Khách hàng'],
        'feature'       => ['controller'=>'Feature','title' => 'Banner'],
        'subscriber'    => ['controller'=>'Subscriber','title' => 'Subscriber'],
        'purchase'       => ['controller' => 'Purchase', 'title' => 'Trả góp'],
        //'coupon' => ['controller' => 'Coupon', 'title' => 'Mã giảm giá'],
        //'subscriber-newsletter'    => ['controller'=>'SubscriberNewsLetter','title' => 'Thư liên hệ'],
        'file'          => ['controller'=>'File','title' => 'File','perm' => ['upload' => 'Upload']],
        'tag'           => ['controller'=>'Tag','title' => 'Tag'],
        'news'          => ['controller'=>'News','title' => 'Tin tức','perm_extra' => ['tag' => 'Gán tag']],
        //'activity'        => ['controller'=>'Activity','title' => 'Hoạt động chính'],
        //'linen'        => ['controller'=>'Linen','title' => 'Công nghệ sợi'],
        'page'          => ['controller'=>'StaticPage','title' => 'Trang tĩnh'],
        'user'          => ['controller'=>'User','title' => 'Người dùng'],
        'role'          => ['controller'=>'Role','title' => 'Phân quyền'],
        'menu'          => ['controller'=>'Menu','title' => 'Menu'],
        'image'         => ['controller'=>'Image','title' => 'Awrads'],
        'config'        => ['controller'=>'Config','title' => 'Cấu hình website', 'form' => 1, 'perm'=>['change' => 'Thay đổi cấu hình']],
        'product'       => ['controller'=>'Product','title' => 'Dự án', 'perm_extra' => ['upload' => 'Upload']],
        // 'brand'         => ['controller'=> 'Brand' , 'title' => 'Thương hiệu'],
        // 'vehicles'         => ['controller'=> 'Vehicles' , 'title' => 'Dòng xe'],
        // 'service'       => ['controller'=>'Service','title' => 'Dịch vụ'],
        // 'status'        => ['controller' => 'Status', 'title' => 'Tình trạng xe'],
        // 'video'         => ['controller' => 'Video', 'title' => 'Video'],
        'icon'          => ['controller' => 'Icon', 'title' => 'People'],
        // 'accessary'     => ['controller' => 'Accessary', 'title' => 'Danh mục phụ tùng'],
        // 'productPrice'  => ['controller' => 'ProductPrice', 'title' => 'Giá sản phẩm'],
        // 'payload'       => ['controller' => 'Payload', 'title' => 'Trọng tải'],
        //'confighome'    => ['controller' => 'ConfigHome', 'title' => 'Cấu hình trang chủ', 'form' => 1, 'perm'=>['change' => 'Thay đổi cấu hình']],
        'page'          => ['controller' => 'PageStatic' , 'title' => "Quản lý trang tĩnh"],
        // 'comment_post'  => ['controller'=>'CommentPost','title' => 'Bình luận Sản phẩm'],
        //'company'      => ['controller'=>'Company','title' => 'Công ty Pavis'],
        'page_intro'    => ['controller' => 'PageIntro' , 'title' => 'Trang giới thiệu'],
//        'subscriber_contribute'    => ['controller'=>'SubscriberContribute','title' => 'Đăng ký đại lý'],
//        'stores'        => ['controller' => 'Stores' , 'title' => "Hệ thống đại lý"],
    ]
];
