<?php

namespace App\Modules\BackEnd\Controllers;

use App\Models\Category;
use App\Models\News;
use App\Models\PageIntro;
use Illuminate\Http\Request;
use App\Models\Page;

use App\Models\Menu as THIS;

class MenuController extends BackendController
{
    protected $timeStamp = 'created';
    protected $recperpage = 9999;

    //config controller, ez for copying and paste
    public function __construct(){
        parent::__construct(new THIS(),[['title' => 'required|max:250', 'type' => 'required']]);
        \View::share('allType', THIS::$menuType);
        \View::share('allOid', THIS::$menuOid);

        //for edit and add
        if($this->form != 'list') {
            $routes = \Lib::getRoutes(true);
            $out = array_merge($routes['public'], $routes['admin']);
            \View::share('routes', json_encode($out));
            \View::share('preview', request('preview'));
            \View::share('view', request('view'));
            \View::share('permList', \Role::getPermissions());
        }

        $this->registerAjax('get-menu', 'ajaxGetMenu', 'edit');
        $this->registerAjax('load-oid', 'ajaxLoadOid', 'edit');
    }

    public function index(Request $request){
        $order = 'type, pid, sort DESC, title';
        if ($request->status != '') {
            $cond[] = ['status', $request->status];
        } else {
            $cond[] = ['status', '!=', -1];
        }
        if($request->title != ''){
            $cond[] = ['title','LIKE','%'.$request->title.'%'];
        }
        $time = explode(' - ', \request('time_between'));
        if(is_array($time)) {
            foreach($time as $k => $t) {
                $timeStamp = \Lib::getTimestampFromVNDate($t);
                if (!$k) {
                    array_push($cond, ['created', '>=', $timeStamp]);
                }else {
                    array_push($cond, ['created', '<=', $timeStamp]);
                }
            }
        }
        if(!empty($cond)) {
            $data = THIS::where($cond)->orderByRaw($order)->paginate($this->recperpage);
        }else{
            $data = THIS::orderByRaw($order)->paginate($this->recperpage);
        }
        return $this->returnView('index', [
            'data' => $this->fetchResult($data),
            'search_data' => $request
        ]);
    }

    public function fetchResult($data){
        $tmp = [];
        foreach($data as $key => $item){
            if(!isset($tmp[$item->type])){
                $tmp[$item->type] = [
                    'title' => THIS::$menuType[$item->type],
                    'type' => $item->type,
                    'menus' => []
                ];
            }
            if($item->pid == 0){
                $tmp[$item->type]['menus'][$item->id] = [
                    'data' => $item,
                    'sub' => []
                ];
                unset($data[$key]);
            }elseif(isset($tmp[$item->type]['menus'][$item->pid])){
                $tmp[$item->type]['menus'][$item->pid]['sub'][$item->id] = [
                    'data' => $item,
                    'sub' => []
                ];
                unset($data[$key]);
            }
        }
        foreach($data as $key => $item){
            foreach ($tmp[$item->type]['menus'] as $i => $menu){
                foreach($menu['sub'] as $k => $sub){
                    if($k == $item->pid){
                        $tmp[$item->type]['menus'][$i]['sub'][$k]['sub'][$item->id] = $item;
                    }
                }
            }
        }
        return $tmp;
    }

    public function beforeSave(Request $request, $ignore_ext = [])
    {
        parent::beforeSave($request); // TODO: Change the autogenerated stub
        if ($request->hasFile('image_seo')) {
            $this->uploadImage($request, $request->title_seo, 'image_seo');
        }
        $this->model->type = $request->type >= 0 ? $request->type : 9;
        $this->model->active = $request->link ;
        $this->model->no_follow = !empty($request->no_follow) ? 1 : 0;
        $this->model->newtab = !empty($request->newtab) ? 1 : 0;
    }

    protected function ajaxGetMenu(Request $request){
        $menu = [];
        if($request->type >= 0){
            $menu = THIS::getMenu($request->type, false, $request->lang);
        }
        return \Lib::ajaxRespond(true, 'ok', $menu);
    }

    protected function ajaxLoadOid(Request $request){
        $menu = [];
        if(isset(THIS::$menuOid[$request->id])){
            $typeObj = THIS::$menuOid[$request->id];
            if($typeObj['table'] == Category::table_name) {
                $lsObj = \DB::table(Category::table_name)->select('id', 'alias', 'title', 'status')->where('type', $typeObj['type'])->get();
                return \Lib::ajaxRespond(true, 'ok', $lsObj);
            }elseif ($typeObj['table'] == News::table_name) {
                $lsObj = \DB::table(News::table_name)->select('id', 'alias', 'title', 'status')->get();
                return \Lib::ajaxRespond(true, 'ok', $lsObj);
            }elseif ($typeObj['table'] == PageIntro::table_name) {
                $lsObj = \DB::table(PageIntro::table_name)->select('id', 'alias', 'title', 'status')->where('status' ,PageIntro::STATUS_ACTIVE )->get();
                return \Lib::ajaxRespond(true, 'ok', $lsObj);
            }elseif ($typeObj['table'] == Page::table_name) {
                $lsObj = \DB::table(Page::table_name)->select('id', 'alias', 'title', 'status')->where('status' ,Page::STATUS_ACTIVE )->get();
                return \Lib::ajaxRespond(true, 'ok', $lsObj);
            }
        }
        return \Lib::ajaxRespond(false, 'Không tìm thấy dữ liệu');
    }
}
