<?php

namespace App\Modules\BackEnd\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Models\IOSeach;
use App\Models\Tag;
use App\Models\Statistics;
use App\Models\ServiceCate;
use App\Models\ServiceNew as THIS;
use App\Models\Author;
use App\Libs\LoadDynamicRouter;

class ServiceController extends BackendController
{
    protected $timeStamp = 'created';
    protected $tagID = 1;
    protected $recperpage = 20;
    //config controller, ez for copying and paste
    public function __construct(){
        parent::__construct(new THIS(),[
            [
                'title' => 'required|max:250',
                // 'title_seo' => 'max:250',
            ],
            [
                'title.required' => 'Tiêu đề không được bỏ trống',
                'title.max' => 'Tiêu đề không được quá 250 ký tự',
            ]

        ]);
        LoadDynamicRouter::loadRoutesFrom('FrontEnd');
        $this->registerAjax('removeimg', 'ajaxItemImgDel', 'delete');
        // \View::share('catOpt', Category::getCat(2));
        // \View::share('tagType', $this->tagID);
    }

    public function ajaxItemImgDel(Request $request)
    {
        if($request->id > 0){
            $data = THIS::where('id', $request->id)->where('image', $request->img)->first();
            if($data){
                $data->image = null;
                $data->save();
            }
            return \Lib::ajaxRespond(true, 'ok', ['json' => 'xóa ảnh']);
        }
        return \Lib::ajaxRespond(false, 'Không tìm thấy dữ liệu');
    }

    public function index(Request $request){
        $order = 'service.created DESC';
        $cond = [];
        if ($request->status != '') {
            $cond[] = ['service.status', $request->status];
        } else {
            $cond[] = ['service.status', '!=', -1];
        }
        if($request->title != ''){
            $cond[] = ['service.title','LIKE','%'.$request->title.'%'];
        }

        if($request->show_on_service_idx > -1) {
            $cond[] = ['service.show_on_service_idx','=',$request->show_on_service_idx];
        }
        
        $time = explode(' - ', \request('time_between'));
        if(is_array($time)) {
            foreach($time as $k => $t) {
                $timeStamp = \Lib::getTimestampFromVNDate($t);
                if (!$k) {
                    array_push($cond, ['service.published', '>=', $timeStamp]);
                }else {
                    array_push($cond, ['service.published', '<=', $timeStamp]);
                }
            }
        }
        if(!empty($cond)) {
            $data = THIS::where($cond)->orderByRaw($order)->paginate($this->recperpage);
        }else{
            $data = THIS::orderByRaw($order)->paginate($this->recperpage);
        }
        // foreach ($data as $key => $value) {
        //     @$value->cate=THIS::find($value->id)->categories()->get();
        // }
        return $this->returnView('index', [
            'lsObj' => $data,
            'search_data' => $request,
            'admin' => '',
            'customer' => ''
        ]);
    }

    public function showAddForm() {
        $preview = request('preview');
        $type_view = request('view', 'full');
        $lsCate = Category::getTreeCateCheckboxByType(3, [], 0);
        return $this->returnView('edit', [
            'preview' => $preview,
            'view' => $type_view,
            'lsCate' => $lsCate
        ]);
    }

    public function showEditForm($id){
        $preview = request('preview');
        $type_view = request('view', 'full');
        $obj = THIS::find($id);
        

        if($obj) {
            $selected = [];
            $categories = $obj->categories->toArray();
            foreach ($categories as $cate) {
                $selected[] = $cate['id'];
            }
            $lsCate = Category::getTreeCateCheckboxByType(3, $selected, $obj->cate_primary);
            set_old($obj);

            return $this->returnView('edit', [
                'obj' => $obj,
                'preview' => $preview,
                'view' => $type_view,
                'lsCate' => $lsCate
            ]);
        }
        return $this->notfound($id);
        
    }

    public function beforeSave(Request $request, $ignore_ext = [])
    {
        parent::beforeSave($request, $ignore_ext); // TODO: Change the autogenerated stub
        // $this->uploadImage($request,$request->title,'image');
        $this->model->views = THIS::VIEWS;
        $this->model->title_seo = !empty($request->title_seo) ? $request->title_seo : $request->title;
        $this->model->author = (\Auth::check()) ? \Auth::user()->id : 'Vô danh';
        $this->model->alias = isset($request->alias) ? $request->alias : str_slug($request->title);
        
        if($this->model->removed == THIS::REMOVED_NO && $this->model->status != -1) {
            if($request->status == 'pending') {
                $this->model->status = THIS::STATUS_INACTIVE;
            }else {
                $this->model->status = @$request->status?:THIS::STATUS_INACTIVE;
            }
        }else {
            $this->model->status = -1;
        }
        if(!empty($request->published)){
            $this->model->published = \Lib::getTimestampFromVNDate($request->published);
        }
        if ($request->hasFile('image_seo')) {
            $this->uploadImage($request, $request->title_seo, 'image_seo');
        }

        // xoa truong thua
        unset($this->model->tags, $this->model->cate_ids, $this->model->files);
    }

    public function afterSave(Request $request)
    {

        // thêm data vào iosearch
        //  mọi thứ đều đc lưu trước khi vào search vì thế vẫn update
        if(!empty($request->cate_ids)) {
            ServiceCate::addCateById($this->editID, $request->cate_ids);
        }
        $old = IOSeach::where([
            ['object_id', $this->model->id],
            ['table', THIS::table_name],
        ])->first();

        if(!$old) {
            //  thêm mới + init
            $old = new IOSeach();
        }
        $old->name  = $this->model->title;
        $old->alias  = $this->model->alias;
        $old->cate_id  = $this->model->cate_id?:0;
        $old->object_id  = $this->model->id;
        $old->table  = THIS::table_name;
        $old->keyword  = $this->model->title;
        $old->created = time();
        $old->save();

    }


}
