<?php


namespace App\Modules\BackEnd\Controllers;

use Illuminate\Http\Request;

use App\Models\SubscriberContribute as THIS;
class SubscriberContributeController extends BackendController
{
    protected $recperpage = 10;

    public function __construct(){
        parent::__construct(new THIS(), [
            [
                'fullname' => 'required|max:250',
                'email' => 'required|email',
            ],
            [
                'fullname.required' => 'Họ và tên không được bỏ trống.',
                'fullname.max' => 'Tiêu đề không được quá 250 ký tự.',
                'email.required' => 'Email không được bỏ trống',
            ]
        ]);
        $this->registerAjax('delete', 'ajaxDelete', 'delete');
        $this->registerAjax('popup-preview', 'ajaxPreview', 'view');
    }

    public function index(Request $request){
        $order = 'created DESC, id DESC';
        $cond = [];

        if($request->fullname != ''){
            $cond[] = ['fullname', 'LIKE' , '%'.$request->fullname.'%'];
        }
        if($request->email != ''){
            $cond[] = ['email','LIKE','%'.$request->email.'%'];
        }
        if($request->phone != ''){
            $cond[] = ['phone','LIKE','%'.$request->phone.'%'];
        }
        if ($request->status != '') {
            $cond[] = ['status', $request->status];
        } else {
            $cond[] = ['status', '!=', -1];
        }
        $time = explode(' - ', \request('time_between'));
        if(is_array($time)) {
            foreach($time as $k => $t) {
                $timeStamp = \Lib::getTimestampFromVNDate($t);
                if (!$k) {
                    array_push($cond, ['created', '>=', $timeStamp]);
                }else {
                    array_push($cond, ['created', '<=', $timeStamp]);
                }
            }
        }
        if(!empty($cond)) {
            $data = THIS::where($cond)->orderByRaw($order)->paginate($this->recperpage);
        }else{
            $data = THIS::where('status','>=', THIS::STATUS_ACTIVE)->orderByRaw($order)->paginate($this->recperpage);
        }
        return $this->returnView('index', [
            'data' => $data,
            'search_data' => $request,
        ]);
    }

    public function showAddForm() {
        $preview = request('preview');
        $type_view = request('view', 'full');
        return $this->returnView('edit', [
            'preview' => $preview,
            'view' => $type_view,
        ]);
    }

    public function beforeSave(Request $request, $ignore_ext = [])
    {
        parent::beforeSave($request, $ignore_ext); // TODO: Change the autogenerated stub
        $this->model->content = json_encode($this->model->content);
        $this->model->created = time();
        $this->model->total_money = intval(str_replace([',','.'], '', $this->model->total_money));
        if($this->model->removed == THIS::REMOVED_NO && $this->model->status != -1) {
            if($request->status == 'pending') {
                $this->model->status = THIS::STATUS_ACTIVE;
            }else {
                $this->model->status = @$request->status?:THIS::STATUS_ACTIVE;
            }
        }else {
            $this->model->status = -1;
        }
    }

    public function showEditForm($id){
        $obj = THIS::find($id);
        if(!empty($obj)){
            set_old($obj);
            $preview = request('preview');
            $type_view = request('view', 'full');
            return $this->returnView('edit', [
                'preview' => $preview,
                'view' => $type_view,
                'obj' => $obj,
            ]);
        }
        return $this->notfound($id);
    }

    function ajaxDelete(Request $request) {
        $id = $request->id?:0;
        if(!$id) {
            return \Lib::ajaxRespond(false, 'Không tìm thấy dữ liệu!');
        }
        $obj = THIS::find($id);
        if(!empty($obj)){
            $removed = ($request->removed == "true") ? THIS::REMOVED_NO : THIS::REMOVED_YES;
//            $obj->update(['removed' => $removed]);
            $obj['removed'] = $removed;
            $obj->save();
            if($request->removed != "true") {
                $this->delete($id);
            }else {
                $obj['status'] = THIS::STATUS_ACTIVE;
                $obj->save();
//                $obj->update(['status' => THIS::STATUS_INACTIVE]);
            }
            return \Lib::ajaxRespond(true, 'Xóa dữ liệu thành công');
        }
        return \Lib::ajaxRespond(false, 'Không tìm thấy bản ghi');

    }

    public function ajaxPreview(Request $request) {
        $obj = THIS::find($request->id);

        if($obj) {
            $tpl = [];
            $tpl['obj'] = $obj->toArray();
            $data = \View::make("BackEnd::pages.subscriber.include.preview", $tpl)->render();
            echo $data;die;
        }
        return \Lib::ajaxRespond(false, 'Không tìm thấy dữ liệu');
    }

}