<?php

namespace App\Modules\BackEnd\Controllers;


use Illuminate\Http\Request;
use App\Models\Vehicles as THIS;

class VehiclesController extends BackendController
{
    protected $recperpage = 9999;
    protected $timeStamp = 'created';
    public function __construct(){
        parent::__construct(new THIS(),[
            [
                'title' => 'required|min:3|max:250',
                // 'sort' => 'numeric',
            ],
            [
                'title.required' => 'Tiêu đề dòng xe không được bỏ trống',
                'title.min' => 'Tiêu đề dòng xe tối thiểu 3 ký tự',
                'title.max' => 'Tiêu đề dòng xe tối đa 250 ký tự',
                // 'sort.numeric' => 'Sắp xếp phải là kiểu số',
            ]
        ]);
        \View::share('type', THIS::getType());
        $this->registerAjax('get-cat', 'ajaxGetCat');
        $this->registerAjax('fetch-cat-lang', 'ajaxFetchCat');
        $this->registerAjax('removeImageCategory' , 'ajaxRemoveImageCat');
    }

    public function index(Request $request){
        // $order = 'type, pid, sort DESC, title';
        $cond = [['status','>',-1]];
    
        if($request->title != ''){
            $cond[] = ['title','LIKE','%'.$request->title.'%'];
        }
        $time = explode(' - ', \request('time_between'));
        if(is_array($time)) {
            foreach($time as $k => $t) {
                $timeStamp = \Lib::getTimestampFromVNDate($t);
                if (!$k) {
                    array_push($cond, ['created', '>=', $timeStamp]);
                }else {
                    array_push($cond, ['created', '<=', $timeStamp]);
                }
            }
        }
        if(!empty($cond)) {
            $data = THIS::where($cond)->where('status' , '>=' , THIS::STATUS_INACTIVE)->orderBy('created', 'DESC')->paginate($this->recperpage);
        }else{
            $data = THIS::where('status' , '>=' , THIS::STATUS_INACTIVE)->orderBy('created', 'DESC')->paginate($this->recperpage);
        }

        return $this->returnView('index', [
            'data' => $data,
            'search_data' => $request
        ]);
    }

    public function beforeSave(Request $request, $ignore_ext = [])
    {
        parent::beforeSave($request, $ignore_ext); // TODO: Change the autogenerated stub
        $this->uploadImage($request,$request->title,'image');

        if ($request->hasFile('image_seo')) {
            $this->uploadImage($request, $request->title_seo, 'image_seo');
        }
        // xoa truong thua
        unset($this->model->files);
    }


    public function showAddForm() {
        $preview = request('preview');
        $type_view = request('view', 'full');
        return $this->returnView('edit', [
            'preview' => $preview,
            'view' => $type_view,
        ]);
    }

    public function showEditForm($id){
        $data = THIS::find($id);
        $preview = request('preview');
        $type_view = request('view', 'full');
        if(empty($data)){
            return $this->notfound($id);
        }
        set_old($data);
        if(isset($data)){
            return $this->returnView('edit', [
                'obj' => $data,
                'preview' => $preview,
                'view' => $type_view,
            ]);
        }
        return $this->notfound($id);
    }

    
}
